plugins {
    id 'java'
}

group = 'me.woomin'
version = '1.0-SNAPSHOT'

repositories {
    mavenCentral()

    maven {
        name = 'papermc'
        url = 'https://repo.papermc.io/repository/maven-public/'
    }
}

dependencies {
    compileOnly 'io.papermc.paper:paper-api:26.2.build.+'
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(25)
    }
}